### ISSUE TITLE
Enhancement request - Add search to open local tables

### ISSUE THREAD

**Issue by jacebenson** [macmorning/snowtools-webext#23]
e.g "Client Scripts" or "sys_client_script" to open the defined table on the specified instance similar to;
https://addons.mozilla.org/en-US/firefox/addon/sn-instances-manager/ this.

**Comment by macmorning** [comment]
I'm wondering, is this really going to save me time as a servicenow dev?
How is it faster than opening the object list directly from my instance tab?
Is this a feature of the linked extension you've been using?

**Comment by macmorning** [comment]
Ok Jace, I'll close this for now then.
