### ISSUE TITLE
Background script execution history?

### ISSUE THREAD

**Issue by macmorning** [macmorning/snowtools-webext#82]
I often miss a list of previously executed background scripts.
It would be nice to have it at hand from the background scripts window and manually save some of them.

**Comment by jacebenson** [comment]
So hey, did you know this is in the platform.. its just in a table that I can not ever remember.  A link might get you close to what you want.  /sys_script_execution_history_list.do

**Comment by macmorning** [comment]
Nice, it has the background script history for the 7 last days. I could show the recent executions, and allow to save some of them as favorites in browser storage.

**Comment by macmorning** [comment]
Done the history part, not the "favorites".

**Comment by macmorning** [comment]
Delivered with 5.0.0 package. Will do the "favorites" part later.
