### ISSUE TITLE
Help for keyboard shortcuts

### ISSUE THREAD

**Issue by chriscogburn** [macmorning/snowtools-webext#86]
I see it mentioned but I can't find what the keyboard commands referenced in [the addon page](https://microsoftedge.microsoft.com/addons/detail/servicenow-tool-belt/ofefboehibiaekjaiaiacalcdeonfbil) notes.

"Keyboard commands: reopen in navpage frame, display technical names of fields and columns"

**Comment by macmorning** [comment]
Hey Chris,
I guess you're using Edge then?
The shortcuts are configured here: edge://extensions/shortcuts

**Comment by chriscogburn** [comment]
> edge://extensions/shortcuts

You are exactly correct! Our company recently started using it and I figured I would give it a try, all the while thinking "am I going to be missing anything from pure Chrome?" -- and this is the first thing! :)

Thanks so much for the quick response!

**Comment by macmorning** [comment]
You're welcome!
I should update the version on Edge though, and the tips available from the extension.
We have absolutely no insight on the usage of the extensions on the Microsoft Store at this time, it doesn't help much :)
