### ISSUE TITLE
Need update to Utah release

### ISSUE THREAD

**Issue by TheNomadBR** [macmorning/snowtools-webext#90]
Hi guys, 

Looks like the tool requires an update to work with Utah release, particularly to the browser tab icon coloring. 

Thanks,

**Comment by macmorning** [comment]
Thanks for the feedback, I'll look into this!

**Comment by macmorning** [comment]
Hello @TheNomadBR, can you please elaborate and describe the issues you have been experiencing on Utah?
I've just booted my Utah dev instance, and for now I didn't notice anything, even witht he tab icon coloring. I'll keep looking.
